module.exports = {
  events: [
    'App Launched',
    'User Finished Registertion',
    'User Logged In',
    'User On Add New Challenge Page',
    'User On Assignments Student Area',
    'User On Challenge Page',
    'User On Forgot Password Page',
    'User On Forgot Password Page 2',
    'User On Forgot Password Page 3',
    'User On Home Page',
    'User On Login Page',
    'User On My Challenges Page',
    'User On Personal Details Page',
    'User On Register Page 1',
    'User On Register Page 2',
    'User On Register Page 3',
    'User On Register Page 4',
    'User On Register Page 5',
    'User On Team Assignments Teacher Area',
    'User On Team Dashboard Teacher Area',
    'User On Team Info Student Area',
    'User On Team Submissions Teacher Area',
    'User On Teams Area',
    'User Started Challenge',
    'User Submited Challenge',
  ],
};
