module.exports = [
  {
    id: 1,
    name: 'React Recoil',
    description: 'In the following project you will be introduced with the advantages of recoil for state management and application efficiency',
    type: 'client-only',
    repository_name: 'suvelocity/recoil-challenge',
    boiler_plate: 'suvelocity/recoil-boilerplate',
    author_id: 1,
    state: 'approved',
    created_at: '2020-10-01 20:00:00',
    updated_at: '2020-10-01 20:00:00',
  },
  {
    id: 2,
    name: 'React - 4 In A Row',
    description: 'The goal of the game is to draw either a vertical, horizontal or diagonal line with four balls of the same player chained together.',
    type: 'client-only',
    repository_name: 'suvelocity/4In-a-row-CHALLENGE',
    boiler_plate: 'suvelocity/4In-a-row-BOILERPLATE',
    author_id: 1,
    state: 'approved',
    created_at: '2020-10-01 20:00:00',
    updated_at: '2020-10-01 20:00:00',
  },
  {
    id: 3,
    name: 'React - Calculator',
    description: 'Welcome! looks like our calculator broke down, please help us fix it!',
    type: 'client-only',
    repository_name: 'suvelocity/calculator-challange-tests',
    boiler_plate: 'suvelocity/calculator-challenge',
    author_id: 1,
    state: 'approved',
    created_at: '2020-10-01 20:00:00',
    updated_at: '2020-10-01 20:00:00',
  },
  {
    id: 4,
    name: 'React - Tv shows',
    description: 'In this challenge we will test your abilities to create a simple react app and using API. Your task is to build a simple IMDB clone for TV shows.',
    type: 'client-only',
    repository_name: 'suvelocity/TV-shows-challenge',
    boiler_plate: 'suvelocity/TV-shows-boilerplate',
    author_id: 1,
    state: 'approved',
    created_at: '2020-10-01 20:00:00',
    updated_at: '2020-10-01 20:00:00',
  },
  {
    id: 5,
    name: 'React - Chat app',
    description: 'Hello friend, today we are going to help you create a simple Chat-App.',
    type: 'fullstack',
    repository_name: 'suvelocity/Chat_App-Challange',
    boiler_plate: 'suvelocity/Chat-App-Template',
    author_id: 1,
    state: 'denied',
    created_at: '2020-10-01 20:00:00',
    updated_at: '2020-10-01 20:00:00',
  },
  {
    id: 6,
    name: 'Js - Drag N Scale',
    description: 'Show your dominance in front end vanilla JavaScript by creating a movable scalable object!',
    type: 'client-only',
    repository_name: 'suvelocity/drag-n-scale',
    boiler_plate: 'suvelocity/DragAndScaleBoilerplate',
    author_id: 1,
    state: 'denied',
    created_at: '2020-10-01 20:00:00',
    updated_at: '2020-10-01 20:00:00',
  },
  {
    id: 7,
    name: 'Mysql - My Nodejs ORM',
    description: 'In this challenge we will be building basic ORM functionality base on Sequelize using mysql2',
    type: 'server-mysql',
    repository_name: 'suvelocity/challenge-sequelize',
    boiler_plate: 'suvelocity/challenge-sequelize-template',
    author_id: 1,
    state: 'denied',
    created_at: '2020-10-01 20:00:00',
    updated_at: '2020-10-01 20:00:00',
  },
  {
    id: 8,
    name: 'JWT - Node.js',
    description: 'Welcome to the Best Authentication Challenge ever existed.',
    type: 'server-only',
    repository_name: 'suvelocity/Authentication-Challenge',
    boiler_plate: 'suvelocity/Authentication-Challenge-TEMPLATE',
    author_id: 1,
    state: 'pending',
    created_at: '2020-10-01 20:00:00',
    updated_at: '2020-10-01 20:00:00',
  },
  {
    id: 9,
    name: 'Promise Implementation',
    description: `The client comes from a religious background and isn't comfortable with the word "promise" being part of their software
    The client wants a new class to replace the Promise, called... Declare`,
    type: 'server-only',
    repository_name: 'suvelocity/PromiseChallenge',
    boiler_plate: 'suvelocity/PromiseBoilerplate',
    author_id: 1,
    state: 'pending',
    created_at: '2020-10-01 20:00:00',
    updated_at: '2020-10-01 20:00:00',
  },
  {
    id: 10,
    name: 'React - Corona dashboard',
    description: 'We need your help to beat the COVID pandemic !!',
    type: 'server-mysql',
    repository_name: 'suvelocity/corona-manager-chalenge',
    boiler_plate: 'suvelocity/corona-pandemic-manager',
    author_id: 1,
    state: 'pending',
    created_at: '2020-10-01 20:00:00',
    updated_at: '2020-10-01 20:00:00',
  },
  {
    id: 11,
    name: 'Analytics Challenge',
    description: 'Use TypeScript with React and Express to build a data analysis system for a mobile payment site',
    type: 'server-only',
    repository_name: 'suvelocity/analytics-tests',
    boiler_plate: 'suvelocity/analytics-challenge-boilerplate',
    author_id: 1,
    state: 'pending',
    created_at: '2020-10-01 20:00:00',
    updated_at: '2020-10-01 20:00:00',
  },
];
