module.exports = [
  {
    id:1,
    author_id:1,
    name: "JWT - Node.js",
    description: "https://github.com/suvelocity/Authentication-Challenge-TEMPLATE",
    type: "static",
    repository_name: "suvelocity/Authentication-Challenge",
    boiler_plate:"suvelocity/Authentication-Challenge-TEMPLATE",
    created_at: "2020-10-01 20:00:00",
    updated_at: "2020-10-01 20:00:00",
  },
  {
    id:2,
    author_id:2,
    name: "React - Calculator",
    description: "https://github.com/suvelocity/calculator-challenge",
    type: "client",
    repository_name: "suvelocity/calculator-challange-tests",
    boiler_plate:"suvelocity/calculator-challenge",
    created_at: "2020-10-01 20:00:00",
    updated_at: "2020-10-01 20:00:00",
  },
  {
    id:3,
    author_id:3,
    name: "Js - Drag N Scale",
    description: "https://github.com/suvelocity/DragAndScaleBoilerplate",
    type: "static",
    repository_name: "suvelocity/drag-n-scale",
    boiler_plate:"suvelocity/DragAndScaleBoilerplate",
    created_at: "2020-10-01 20:00:00",
    updated_at: "2020-10-01 20:00:00",
  }
]