module.exports = [
  {
    id: 1,
    challenge_id: 1,
    user_id: 1,
    state: 'SUCCESS',
    solution_repository: 'Moran1324/Authentication-Challenge-SOLUTION',
    created_at: new Date(Date.now().valueOf() - (1 * 24 * 60 * 60 * 1000)),
    updated_at: new Date(Date.now().valueOf() - (1 * 24 * 60 * 60 * 1000)),
  },
  {
    id: 2,
    challenge_id: 2,
    user_id: 1,
    state: 'FAIL',
    solution_repository: 'OfirSimhi1612/Auth-Challenge',
    created_at: new Date(Date.now().valueOf() - (1 * 24 * 60 * 60 * 1000)),
    updated_at: new Date(Date.now().valueOf() - (1 * 24 * 60 * 60 * 1000)),
  },
  {
    id: 3,
    challenge_id: 3,
    user_id: 1,
    state: 'SUCCESS',
    solution_repository: 'michaelbyalsky/Authentication-Challenge-SOLUTION',
    created_at: new Date(Date.now().valueOf() - (2 * 24 * 60 * 60 * 1000)),
    updated_at: new Date(Date.now().valueOf() - (2 * 24 * 60 * 60 * 1000)),
  },
  {
    id: 4,
    challenge_id: 4,
    user_id: 1,
    state: 'FAIL',
    solution_repository: 'Moran1324/Authentication-Challenge-SOLUTION',
    created_at: new Date(Date.now().valueOf() - (2 * 24 * 60 * 60 * 1000)),
    updated_at: new Date(Date.now().valueOf() - (2 * 24 * 60 * 60 * 1000)),
  },
  {
    id: 5,
    challenge_id: 5,
    user_id: 1,
    state: 'SUCCESS',
    solution_repository: 'OfirSimhi1612/Auth-Challenge',
    created_at: new Date(Date.now().valueOf() - (3 * 24 * 60 * 60 * 1000)),
    updated_at: new Date(Date.now().valueOf() - (3 * 24 * 60 * 60 * 1000)),
  },
  {
    id: 6,
    challenge_id: 6,
    user_id: 1,
    state: 'FAIL',
    solution_repository: 'Moran1324/Authentication-Challenge-SOLUTION',
    created_at: new Date(Date.now().valueOf() - (3 * 24 * 60 * 60 * 1000)),
    updated_at: new Date(Date.now().valueOf() - (3 * 24 * 60 * 60 * 1000)),
  },
  {
    id: 7,
    challenge_id: 7,
    user_id: 1,
    state: 'SUCCESS',
    solution_repository: 'Moran1324/Authentication-Challenge-SOLUTION',
    created_at: new Date(Date.now().valueOf() - (4 * 24 * 60 * 60 * 1000)),
    updated_at: new Date(Date.now().valueOf() - (4 * 24 * 60 * 60 * 1000)),
  },
  {
    id: 8,
    challenge_id: 8,
    user_id: 1,
    state: 'FAIL',
    solution_repository: 'michaelbyalsky/Authentication-Challenge-SOLUTION',
    created_at: new Date(Date.now().valueOf() - (5 * 24 * 60 * 60 * 1000)),
    updated_at: new Date(Date.now().valueOf() - (5 * 24 * 60 * 60 * 1000)),
  },
  {
    id: 9,
    challenge_id: 9,
    user_id: 1,
    state: 'SUCCESS',
    solution_repository: 'David12/Authentication-Challenge-SOLUTION',
    created_at: new Date(Date.now().valueOf() - (6 * 24 * 60 * 60 * 1000)),
    updated_at: new Date(Date.now().valueOf() - (6 * 24 * 60 * 60 * 1000)),
  },
  {
    id: 10,
    challenge_id: 10,
    user_id: 1,
    state: 'FAIL',
    solution_repository: 'OfirSimhi1612/Auth-Challenge',
    created_at: new Date(Date.now().valueOf() - (6 * 24 * 60 * 60 * 1000)),
    updated_at: new Date(Date.now().valueOf() - (6 * 24 * 60 * 60 * 1000)),
  },
  {
    id: 11,
    challenge_id: 1,
    user_id: 2,
    state: 'FAIL',
    solution_repository: 'David12/Authentication-Challenge-SOLUTION',
    created_at: new Date(Date.now().valueOf() - (1 * 24 * 60 * 60 * 1000)),
    updated_at: new Date(Date.now().valueOf() - (1 * 24 * 60 * 60 * 1000)),
  },
  {
    id: 12,
    challenge_id: 2,
    user_id: 2,
    state: 'SUCCESS',
    solution_repository: 'OfirSimhi1612/Auth-Challenge',
    created_at: new Date(Date.now().valueOf() - (1 * 24 * 60 * 60 * 1000)),
    updated_at: new Date(Date.now().valueOf() - (1 * 24 * 60 * 60 * 1000)),
  },
  {
    id: 13,
    challenge_id: 2,
    user_id: 2,
    state: 'FAIL',
    solution_repository: 'michaelbyalsky/Authentication-Challenge-SOLUTION',
    created_at: new Date(Date.now().valueOf() - (2 * 24 * 60 * 60 * 1000)),
    updated_at: new Date(Date.now().valueOf() - (2 * 24 * 60 * 60 * 1000)),
  },
  {
    id: 14,
    challenge_id: 4,
    user_id: 2,
    state: 'SUCCESS',
    solution_repository: 'Moran1324/Authentication-Challenge-SOLUTION',
    created_at: new Date(Date.now().valueOf() - (2 * 24 * 60 * 60 * 1000)),
    updated_at: new Date(Date.now().valueOf() - (2 * 24 * 60 * 60 * 1000)),
  },
  {
    id: 15,
    challenge_id: 5,
    user_id: 2,
    state: 'FAIL',
    solution_repository: 'OfirSimhi1612/Auth-Challenge',
    created_at: new Date(Date.now().valueOf() - (3 * 24 * 60 * 60 * 1000)),
    updated_at: new Date(Date.now().valueOf() - (3 * 24 * 60 * 60 * 1000)),
  },
  {
    id: 16,
    challenge_id: 5,
    user_id: 2,
    state: 'SUCCESS',
    solution_repository: 'David12/Authentication-Challenge-SOLUTION',
    created_at: new Date(Date.now().valueOf() - (3 * 24 * 60 * 60 * 1000)),
    updated_at: new Date(Date.now().valueOf() - (3 * 24 * 60 * 60 * 1000)),
  },
  {
    id: 17,
    challenge_id: 7,
    user_id: 2,
    state: 'FAIL',
    solution_repository: 'David12/Authentication-Challenge-SOLUTION',
    created_at: new Date(Date.now().valueOf() - (4 * 24 * 60 * 60 * 1000)),
    updated_at: new Date(Date.now().valueOf() - (4 * 24 * 60 * 60 * 1000)),
  },
  {
    id: 18,
    challenge_id: 9,
    user_id: 2,
    state: 'SUCCESS',
    solution_repository: 'michaelbyalsky/Authentication-Challenge-SOLUTION',
    created_at: new Date(Date.now().valueOf() - (5 * 24 * 60 * 60 * 1000)),
    updated_at: new Date(Date.now().valueOf() - (5 * 24 * 60 * 60 * 1000)),
  },
  {
    id: 19,
    challenge_id: 9,
    user_id: 2,
    state: 'FAIL',
    solution_repository: 'Moran1324/Authentication-Challenge-SOLUTION',
    created_at: new Date(Date.now().valueOf() - (6 * 24 * 60 * 60 * 1000)),
    updated_at: new Date(Date.now().valueOf() - (6 * 24 * 60 * 60 * 1000)),
  },
  {
    id: 20,
    challenge_id: 9,
    user_id: 2,
    state: 'SUCCESS',
    solution_repository: 'OfirSimhi1612/Auth-Challenge',
    created_at: new Date(Date.now().valueOf() - (6 * 24 * 60 * 60 * 1000)),
    updated_at: new Date(Date.now().valueOf() - (6 * 24 * 60 * 60 * 1000)),
  },
  {
    id: 21,
    challenge_id: 2,
    user_id: 3,
    state: 'SUCCESS',
    solution_repository: 'Moran1324/Authentication-Challenge-SOLUTION',
    created_at: new Date(Date.now().valueOf() - (1 * 24 * 60 * 60 * 1000)),
    updated_at: new Date(Date.now().valueOf() - (1 * 24 * 60 * 60 * 1000)),
  },
  {
    id: 22,
    challenge_id: 2,
    user_id: 3,
    state: 'FAIL',
    solution_repository: 'OfirSimhi1612/Auth-Challenge',
    created_at: new Date(Date.now().valueOf() - (1 * 24 * 60 * 60 * 1000)),
    updated_at: new Date(Date.now().valueOf() - (1 * 24 * 60 * 60 * 1000)),
  },
  {
    id: 23,
    challenge_id: 2,
    user_id: 3,
    state: 'SUCCESS',
    solution_repository: 'michaelbyalsky/Authentication-Challenge-SOLUTION',
    created_at: new Date(Date.now().valueOf() - (2 * 24 * 60 * 60 * 1000)),
    updated_at: new Date(Date.now().valueOf() - (2 * 24 * 60 * 60 * 1000)),
  },
  {
    id: 24,
    challenge_id: 4,
    user_id: 3,
    state: 'FAIL',
    solution_repository: 'Moran1324/Authentication-Challenge-SOLUTION',
    created_at: new Date(Date.now().valueOf() - (2 * 24 * 60 * 60 * 1000)),
    updated_at: new Date(Date.now().valueOf() - (2 * 24 * 60 * 60 * 1000)),
  },
  {
    id: 25,
    challenge_id: 5,
    user_id: 3,
    state: 'SUCCESS',
    solution_repository: 'OfirSimhi1612/Auth-Challenge',
    created_at: new Date(Date.now().valueOf() - (3 * 24 * 60 * 60 * 1000)),
    updated_at: new Date(Date.now().valueOf() - (3 * 24 * 60 * 60 * 1000)),
  },
  {
    id: 26,
    challenge_id: 7,
    user_id: 3,
    state: 'FAIL',
    solution_repository: 'Moran1324/Authentication-Challenge-SOLUTION',
    created_at: new Date(Date.now().valueOf() - (3 * 24 * 60 * 60 * 1000)),
    updated_at: new Date(Date.now().valueOf() - (3 * 24 * 60 * 60 * 1000)),
  },
  {
    id: 27,
    challenge_id: 7,
    user_id: 3,
    state: 'SUCCESS',
    solution_repository: 'Moran1324/Authentication-Challenge-SOLUTION',
    created_at: new Date(Date.now().valueOf() - (4 * 24 * 60 * 60 * 1000)),
    updated_at: new Date(Date.now().valueOf() - (4 * 24 * 60 * 60 * 1000)),
  },
  {
    id: 28,
    challenge_id: 10,
    user_id: 3,
    state: 'FAIL',
    solution_repository: 'michaelbyalsky/Authentication-Challenge-SOLUTION',
    created_at: new Date(Date.now().valueOf() - (5 * 24 * 60 * 60 * 1000)),
    updated_at: new Date(Date.now().valueOf() - (5 * 24 * 60 * 60 * 1000)),
  },
  {
    id: 29,
    challenge_id: 10,
    user_id: 3,
    state: 'SUCCESS',
    solution_repository: 'David12/Authentication-Challenge-SOLUTION',
    created_at: new Date(Date.now().valueOf() - (6 * 24 * 60 * 60 * 1000)),
    updated_at: new Date(Date.now().valueOf() - (6 * 24 * 60 * 60 * 1000)),
  },
  {
    id: 30,
    challenge_id: 10,
    user_id: 3,
    state: 'FAIL',
    solution_repository: 'OfirSimhi1612/Auth-Challenge',
    created_at: new Date(Date.now().valueOf() - (1 * 24 * 60 * 60 * 1000)),
    updated_at: new Date(Date.now().valueOf() - (1 * 24 * 60 * 60 * 1000)),
  },
  {
    id: 31,
    challenge_id: 1,
    user_id: 4,
    state: 'FAIL',
    solution_repository: 'David12/Authentication-Challenge-SOLUTION',
    created_at: new Date(Date.now().valueOf() - (1 * 24 * 60 * 60 * 1000)),
    updated_at: new Date(Date.now().valueOf() - (1 * 24 * 60 * 60 * 1000)),
  },
  {
    id: 32,
    challenge_id: 2,
    user_id: 4,
    state: 'SUCCESS',
    solution_repository: 'OfirSimhi1612/Auth-Challenge',
    created_at: new Date(Date.now().valueOf() - (1 * 24 * 60 * 60 * 1000)),
    updated_at: new Date(Date.now().valueOf() - (1 * 24 * 60 * 60 * 1000)),
  },
  {
    id: 33,
    challenge_id: 3,
    user_id: 4,
    state: 'FAIL',
    solution_repository: 'michaelbyalsky/Authentication-Challenge-SOLUTION',
    created_at: new Date(Date.now().valueOf() - (2 * 24 * 60 * 60 * 1000)),
    updated_at: new Date(Date.now().valueOf() - (2 * 24 * 60 * 60 * 1000)),
  },
  {
    id: 34,
    challenge_id: 4,
    user_id: 4,
    state: 'SUCCESS',
    solution_repository: 'Moran1324/Authentication-Challenge-SOLUTION',
    created_at: new Date(Date.now().valueOf() - (2 * 24 * 60 * 60 * 1000)),
    updated_at: new Date(Date.now().valueOf() - (2 * 24 * 60 * 60 * 1000)),
  },
  {
    id: 35,
    challenge_id: 5,
    user_id: 4,
    state: 'FAIL',
    solution_repository: 'OfirSimhi1612/Auth-Challenge',
    created_at: new Date(Date.now().valueOf() - (3 * 24 * 60 * 60 * 1000)),
    updated_at: new Date(Date.now().valueOf() - (3 * 24 * 60 * 60 * 1000)),
  },
  {
    id: 36,
    challenge_id: 7,
    user_id: 4,
    state: 'SUCCESS',
    solution_repository: 'David12/Authentication-Challenge-SOLUTION',
    created_at: new Date(Date.now().valueOf() - (3 * 24 * 60 * 60 * 1000)),
    updated_at: new Date(Date.now().valueOf() - (3 * 24 * 60 * 60 * 1000)),
  },
  {
    id: 37,
    challenge_id: 7,
    user_id: 4,
    state: 'FAIL',
    solution_repository: 'David12/Authentication-Challenge-SOLUTION',
    created_at: new Date(Date.now().valueOf() - (4 * 24 * 60 * 60 * 1000)),
    updated_at: new Date(Date.now().valueOf() - (4 * 24 * 60 * 60 * 1000)),
  },
  {
    id: 38,
    challenge_id: 8,
    user_id: 4,
    state: 'SUCCESS',
    solution_repository: 'michaelbyalsky/Authentication-Challenge-SOLUTION',
    created_at: new Date(Date.now().valueOf() - (5 * 24 * 60 * 60 * 1000)),
    updated_at: new Date(Date.now().valueOf() - (5 * 24 * 60 * 60 * 1000)),
  },
  {
    id: 39,
    challenge_id: 9,
    user_id: 4,
    state: 'FAIL',
    solution_repository: 'Moran1324/Authentication-Challenge-SOLUTION',
    created_at: new Date(Date.now().valueOf() - (6 * 24 * 60 * 60 * 1000)),
    updated_at: new Date(Date.now().valueOf() - (6 * 24 * 60 * 60 * 1000)),
  },
  {
    id: 40,
    challenge_id: 10,
    user_id: 4,
    state: 'SUCCESS',
    solution_repository: 'OfirSimhi1612/Auth-Challenge',
    created_at: new Date(Date.now().valueOf()),
    updated_at: new Date(Date.now().valueOf()),
  },
];
