module.exports = {
  user: {
    firstName: "Matan",
    lastName: "Greenvald",
    userName: "matanGreenvald",
    password: "12345678",
    email: "mgk@gmail.com",
    birthDate: "02-07-1998",
    country: "Israel",
    city: "Tel Aviv",
    phoneNumber: "0508864599",
    githubAccount: "MTN-G",
    reasonOfRegistration: "HUNGRY",
    securityQuestion: "Where was your best family vacation as a kid?",
    securityAnswer: "Switzerland",
  },
  reg: {
    firstName: "Matan",
    lastName: "Greenvald",
    userName: "matan2798",
    password: "12345678",
    email: "mgk@gmail.com",
    birthDate: "02-07-1998",
    country: "Israel",
    city: "Tel Aviv",
    phoneNumber: "0508864599",
    githubAccount: "MTN-G",
    reasonOfRegistration: "HUNGRY",
    securityQuestion: "Where was your best family vacation as a kid?",
    securityAnswer: "Switzerland",
  },
  login: {
    userName: "matanGreenvald",
    password: "12345678",
    rememberMe: "false"
  },
  user2: {
    firstName: "Matan",
    lastName: "Greenvald",
    userName: "MTN2798",
    password: "12345678",
    email: "mgk@gmail.com",
    birthDate: "02-07-1998",
    country: "Israel",
    city: "Tel Aviv",
    phoneNumber: "0508864599",
    githubAccount: "MTN-G",
    reasonOfRegistration: "HUNGRY",
    securityQuestion: "Where was your best family vacation as a kid?",
    securityAnswer: "Switzerland",
  },
  resetPassword : {
    userName: "MTN2798",
    password: "12345678",
    rememberMe: "false",
  },
};