module.exports = [
  {
    team_id: 1,
    user_id: 1,
    created_at: new Date(),
    updated_at: new Date(),
    permission: 'teacher',
  },
  {
    team_id: 1,
    user_id: 2,
    created_at: new Date(),
    updated_at: new Date(),
    permission: 'student',
  },
  {
    team_id: 1,
    user_id: 3,
    created_at: new Date(),
    updated_at: new Date(),
    permission: 'teacher',
  },
  {
    team_id: 1,
    user_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
    permission: 'student',
  },
  {
    team_id: 2,
    user_id: 1,
    created_at: new Date(),
    updated_at: new Date(),
    permission: 'teacher',
  },
  {
    team_id: 2,
    user_id: 2,
    created_at: new Date(),
    updated_at: new Date(),
    permission: 'student',
  },
  {
    team_id: 2,
    user_id: 3,
    created_at: new Date(),
    updated_at: new Date(),
    permission: 'student',
  },
  {
    team_id: 2,
    user_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
    permission: 'student',
  },
  {
    team_id: 3,
    user_id: 1,
    created_at: new Date(),
    updated_at: new Date(),
    permission: 'student',
  },
  {
    team_id: 3,
    user_id: 3,
    created_at: new Date(),
    updated_at: new Date(),
    permission: 'student',
  },
  {
    team_id: 3,
    user_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
    permission: 'teacher',
  },
];
