module.exports = [
  {
    id: 1,
    first_name: 'cyber4S',
    last_name: 'suvelocity',
    user_name: 'suvelocity',
    password: '12345678',
    email: 'suvelocity@gmail.com',
    birth_date: new Date('1997/06/17'),
    country: 'Israel',
    city: 'Tel Aviv',
    phone_number: '0508864599',
    github_account: 'suvelocity',
    reason_of_registration: "'Challenge Myself'",
    security_question: 'Who was your childhood hero?',
    security_answer: 'superman',
    permission: 'admin',
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 2,
    first_name: 'cyber4S',
    last_name: 'suvelocity',
    user_name: 'regularUser',
    password: '12345678',
    email: 'regularUser@gmail.com',
    birth_date: new Date('1997/06/17'),
    country: 'Israel',
    city: 'Tel Aviv',
    phone_number: '0508864599',
    github_account: 'suvelocity1',
    reason_of_registration: "'Challenge Myself'",
    security_question: 'Who was your childhood hero?',
    security_answer: 'superman',
    permission: 'user',
    created_at: new Date(),
    updated_at: new Date(),
  },
];