# This is a basic workflow to help you get started with Actions

name: CI-Client

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  pull_request:
    branches: [master, staging, cloudrun-staging] # if github changes the 'master' to 'main'

    # we will change that name to 'main'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup node  (Node.js ${{ matrix.node-version }})
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install client dependencies
        run: npm ci
        working-directory: ./client
      - name: Run web server
        run: npm start & npx wait-on http://localhost:3000
        working-directory: ./client
      - name: Jest run
        run: npm run test
        working-directory: ./client
